version: "3.7"

services:
    nginx:
        build: ./nginx
        container_name:  nginx
        restart: always
        #  port allows the host machine to link to container
        # pass 80 from host machine to 80 of the image filesystem
        ports:
            - "80:80"

    backend:
        # look for dockerfile and build the container
        build: ./backend
        container_name:  backend
        restart: always
        # set enviornemt variables
        environment: 
            - APP_NAME=MyFlaskApp
        #  mount the volumes so we can change code and hot reload
        volumes:
            - './backend:/backend'
        #  expose port on the container, only to other containers
        expose:
            - 8080

    frontend:
        build: ./frontend
        container_name:  frontend
        restart: always
        #  mount the volumes so we can change code and hot reload
        volumes:
            - './frontend:/frontend'

        #  port allows the host machine to link to container
        #  8000 for vue ui, 8080 for our vue app
        ports:
            - "8000:8000"
            - "8080:8080"
        expose:
            - 8080

    mongodb:
        image: mongo: 4.2.5-bionic
        container_name:  mongodb
        restart: always
        environment:
            # provide your credentials here
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=rootpassword
        volumes:
            - './database:/data/db'
        ports:
            - "27017:27017"
            - "27018:27018"
            - "27019:27019"
        expose:
            - 27017
            - 27018
            - 27019

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example